server:
  port: 8085
  servlet:
    context-path: /api

spring:
  application:
    name: online-banking-system
  
  datasource:
    # MySQL Configuration
    url: jdbc:mysql://localhost:3306/obs_banking_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  
  # security:
  #   user:
  #     name: admin
  #     password: admin123

  # Mail Configuration - Gmail SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:ananthagunde@gmail.com}
    password: ${MAIL_PASSWORD:iryt qoeb dwls wabf}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    default-encoding: UTF-8
    test-connection: false

app:
  jwt:
    # NOTE: For demo/testing only. Replace with a secure value in production (>=256-bit random key). 
    secret: 2f3c9a7e8b1d4f6a2c5e7d9f0a1b3c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b
    expiration: 86400000 # 24 hours

# Logging
logging:
  level:
    '[com.obd]': DEBUG
    '[org.springframework.security]': DEBUG

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
